FROM continuumio/anaconda3:4.2.0

RUN conda install plotly matplotlib pyqt=4.11

# to reduce startup time, build font cache for matplotlib
RUN python -c "import matplotlib.pyplot"

COPY ./stream-stdin.py /scripts/stream-stdin.py
