FROM continuumio/miniconda3:4.1.11

RUN conda install plotly matplotlib pyqt=4.11

# to reduce startup time, build font cache for matplotlib
RUN python -c "import matplotlib.pyplot"

COPY ./stream-stdin.py /scripts/stream-stdin.py
